kind: Deployment
metadata:
  name: {{ deployment_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ deployment_name }}
  template:
    metadata:
      labels:
        app: {{ deployment_name }}
    spec:
      containers:
      - name: {{ deployment_name }}
        image: {{ container_image }}:latest
        ports:
        - containerPort: 8080